server:
  port: 8888

management:
  security:
    enabled: false

spring:
  application:
    name: config-server
  cloud:
    bus:
      enabled: true
    config:
      server:
        git:
          uri: https://github.com/kevinnguyenai/my-java-microservices.git
          search-paths: config-repo
          basedir: config-repo
          default-label: default        
  rabbitmq:
    host: localhost
    port: 5672    
    
security:
  user:
    name: configUser
    password: configPassword
    role: SYSTEM
    
---
spring:
  profiles: docker
  rabbitmq:
    host: rabbitmq
    port: 5672
  
